// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWA1eJDDobweFwCQHAbi4FrDtdtAjYnuc',
    appId: '1:831048811566:web:37bd51ac0d0f59395d4bbf',
    messagingSenderId: '831048811566',
    projectId: 'schematic-5cd75',
    authDomain: 'schematic-5cd75.firebaseapp.com',
    storageBucket: 'schematic-5cd75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUWgsT0tXYKzGhACLiCWsVD_wRJXQKDSg',
    appId: '1:831048811566:android:035c174732b1abe05d4bbf',
    messagingSenderId: '831048811566',
    projectId: 'schematic-5cd75',
    storageBucket: 'schematic-5cd75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpyKShkQVuxCg1fYR4ZF-iZjaP3WkRTp0',
    appId: '1:831048811566:ios:f86cb87729c4087f5d4bbf',
    messagingSenderId: '831048811566',
    projectId: 'schematic-5cd75',
    storageBucket: 'schematic-5cd75.appspot.com',
    iosBundleId: 'com.shcematic.app',
  );

}